# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9250f64aa93bbc8cb4262cb6340b1d83b3ab06753045533ca2eed5481bbb71649c01fce99d3534c3d991b2f7586f205f07547c2a5e7f8fef4d039ab88da287e4

test:
  secret_key_base: ef03af9da04579471f639feb9ba6f4a49fe1e7aa79753387073f8338bc4c69fe97e6a3f9387dffc00730306d1cef87300153d041f65bafae0a93b05ce427a130

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
